name: automatic_filter

on:
  schedule:
    - cron: "5 0 * * *" # every day at 00:05

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: create formatted email
        run: python run.py 

      - name: send email
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: filtered arxiv submissions
          to: m.serraperalta@tudelft.nl
          from: marcserraperalta@gmail.com
          html_body: file://formatted_email.html
          ignore_cert: true
